[package]
name = "mojito_expr"
version.workspace = true
edition.workspace = true

[dependencies]
bitvec = { workspace = true }
mojito_common = { workspace = true }
mojito_parser = { workspace = true }
thiserror = { workspace = true }
