[workspace]
members = [
    "src/common",
    "src/cypher",
    "src/db",
    "src/parser",
    "src/storage",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
mojito_common = { path = "src/common" }
mojito_cypher = { path = "src/cypher" }
mojito_db = { path = "src/db" }
mojito_parser = { path = "src/parser" }
mojito_storage = { path = "src/storage" }

# other
bytes = "1.10.1"
either = "1.15.0"
itertools = "0.14.0"
thiserror = "2.0.12"

# dev-depencies
insta = { version = "1.43.1", features = ["yaml"] }
tempfile = "3.5.0"

[profile.dev.package]
# make insta run faster
insta.opt-level = 3
similar.opt-level = 3
