[workspace]
members = [
  "src/common",
  "src/cypher",
  "src/db",
  "src/parser",
  "src/storage",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
mojito_common = { path = "src/common" }
mojito_parser = { path = "src/parser" }
mojito_storage = { path = "src/storage" }
mojito_cypher = { path = "src/cypher" }
mojito_db = { path = "src/db" }

# other
either = "1.15.0"
thiserror = "2.0.12"
bytes = "1.10.1"

# dev-depencies
tempfile = "3.5.0"
