[workspace]
members = [
    "src/parser",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
mojito_parser = { path = "src/parser" }
# other dependencies can be added here
either = "1.15.0"
