[workspace]
members = [
    "src/parser", 
    "src/storage",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
mojito_parser = { path = "src/parser" }
mojito_storage = { path = "src/storage" }
# other dependencies can be added here
either = "1.15.0"
