[package]
name = "mojito_catalog"
version.workspace = true
edition.workspace = true

[dependencies]

mojito_common = { workspace = true }
mojito_expr = { workspace = true }
mojito_storage = { workspace = true }
