[package]
name = "elio_catalog"
version.workspace = true
edition.workspace = true

[dependencies]
elio_common = { workspace = true }
elio_expr = { workspace = true }
elio_storage = { workspace = true }
thiserror = { workspace = true }
