[package]
name = "cmd"
version.workspace = true
edition.workspace = true

[[bin]]
name = "elio"
path = "bin/elio.rs"

[dependencies]
clap = { workspace = true, features = ["derive", "cargo"] }
elio_core = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true }
