[package]
name = "mojito_cypher"
version.workspace = true
edition.workspace = true

[dependencies]
mojito_common = { workspace = true }
mojito_parser = { workspace = true }
mojito_storage = { workspace = true }
thiserror = { workspace = true }
