[package]
name = "mojito_parser"
version = {workspace = true}
edition = {workspace = true}

[dependencies]
peg = "0.8.5"
derive_more = { version = "2", features = [ "display" ] }
# workspace
either = { workspace = true}