[package]
name = "mojito_core"
version.workspace = true
edition.workspace = true

[dependencies]
# workspace
mojito_common = { workspace = true }
mojito_cypher = { workspace = true }
mojito_storage = { workspace = true }
thiserror = { workspace = true }
# other
