[package]
name = "mojito_common"
version.workspace = true
edition.workspace = true

[dependencies]
bytes = { workspace = true }
derive_more = { workspace = true, features = ["full"] }
ordered-float = { workspace = true }
